### ISSUE TITLE
Render bezier using cairo ?

### ISSUE THREAD

**Issue by stuaxo** [dhermes/bezier#124]
Hi,
   Any idea how I can render a bezier from this library using cairo paths ?

Cairo has curve_to which takes 3 parameters:

https://pycairo.readthedocs.io/en/latest/reference/context.html?highlight=curve_to

S

**Comment by dhermes** [comment]
I'm not familiar with the Cairo API. It seems like the support in Cairo is for B&#xe9;zier curves of specific degree (e.g. cubic), so you'd just enter the control points. If you had a generic degree, you'd render by turning the curve into a piecewise line with endpoints at evaluated points on the curve.

**Comment by stuaxo** [comment]
The paths can be made up of a few different elements, curves ("curve to") and straight lines ("line to") - I'm not sure how to represent these, where to put the control points (at the ends of the curve?).

**Comment by dhermes** [comment]
@stuaxo Can you give me a simple working example and then I can try to chime on / modify it?

**Comment by stuaxo** [comment]
Hi,
  Thanks for being patient on this ticket, real life has got in the way of vector exploration.

Here is a jupyter notebook,

https://github.com/stuaxo/cairo-jupyter/blob/playground/demos/path_elements.ipynb

You can run it here
https://mybinder.org/v2/gh/stuaxo/cairo-jupyter/playground?filepath=demos%2Fpath_elements.ipynb

I've added a function to output the elements inside each kind of path, and 3 kinds of shape

- rectangle - only straight lines
- a partial circle - just curves
- rounded rectangle from the cairo cookbook - a mix of curves and straights

I'm guessing the shape made of curves will be the most straight forward to port.. I would have made a more interesting curvey shape, but time hasn't permitted it.

The "move to" element in these paths can be ignored for now, since this is just to set the origin of these shapes.

I've filled the shapes, but I could have chosen stroke instead.

**Comment by dhermes** [comment]
Sorry for my delay. I was finishing my thesis (which is now done!). I'm digging in now.

**Comment by dhermes** [comment]
So it seems to me that Cairo supports cubic Bézier curves, e.g.: https://www.cairographics.org/manual/cairo-Paths.html#cairo-curve-to

One could certainly support this with `bezier` but using [`Curve.plot()`][1] gives more flexibility. To emulate that flexibility you could do what `Curve.plot()` [does][2] and just use `line_to`. (Example to follow soon.)

[1]: https://bezier.readthedocs.io/en/0.8.0/reference/bezier.curve.html#bezier.curve.Curve.plot
[2]: https://github.com/dhermes/bezier/blob/d0d0e3236c1cff29137ab88976fb88dc5583928d/src/bezier/curve.py#L244

**Comment by dhermes** [comment]
OK, here is an example of how you'd do it.

```python
import bezier
import cairocffi as cairo
import numpy as np
import seaborn


def example1():
    # From https://pycairo.readthedocs.io/en/latest/
    surface = cairo.SVGSurface("example1.svg", 200, 200)
    context = cairo.Context(surface)
    x, y, x1, y1 = 0.1, 0.5, 0.4, 0.9
    x2, y2, x3, y3 = 0.6, 0.1, 0.9, 0.5
    context.scale(200, 200)
    context.set_line_width(0.04)
    context.move_to(x, y)
    context.curve_to(x1, y1, x2, y2, x3, y3)
    context.stroke()
    context.set_source_rgba(1, 0.2, 0.2, 0.6)
    context.set_line_width(0.02)
    context.move_to(x, y)
    context.line_to(x1, y1)
    context.move_to(x2, y2)
    context.line_to(x3, y3)
    context.stroke()
    surface.finish()


def example2():
    x, y, x1, y1 = 0.1, 0.5, 0.4, 0.9
    x2, y2, x3, y3 = 0.6, 0.1, 0.9, 0.5
    nodes = np.asfortranarray([[x, x1, x2, x3], [y, y1, y2, y3]])
    # Pixel coordinates are "opposite" than data coordinates.
    nodes[1, :] *= -1
    curve = bezier.Curve(nodes, degree=3, _copy=False)
    ax = curve.plot(256, color="black")
    ax.plot([x, x1], [-y, -y1], color="red", alpha=0.5)
    ax.plot([x2, x3], [-y2, -y3], color="red", alpha=0.5)
    ax.axis("scaled")
    ax.figure.savefig("example2.svg", bbox_inches="tight")


def example3():
    x, x1, x2 = 0.0, 0.5, 1.0
    y, y1, y2 = 1.0, -1.0, 1.0
    nodes = np.asfortranarray([[x, x1, x2], [y, y1, y2]])
    curve = bezier.Curve(nodes, degree=2, _copy=False)

    N = 256
    s_vals = np.linspace(0.0, 1.0, N)
    points = curve.evaluate_multi(s_vals)
    x_vals = points[0, :]
    y_vals = points[1, :]

    surface = cairo.SVGSurface("example3.svg", 200, 200)
    context = cairo.Context(surface)
    context.scale(200, 200)
    context.set_line_width(0.01)

    context.move_to(x_vals[0], y_vals[0])
    for i in range(N):
        context.line_to(x_vals[i], y_vals[i])
    context.stroke()

    surface.finish()


def example4():
    x, x1, x2 = 0.0, 0.5, 1.0
    y, y1, y2 = 1.0, -1.0, 1.0
    nodes = np.asfortranarray([[x, x1, x2], [y, y1, y2]])
    # Pixel coordinates are "opposite" than data coordinates.
    nodes[1, :] *= -1
    curve = bezier.Curve(nodes, degree=2, _copy=False)
    ax = curve.plot(256, color="black")
    ax.axis("scaled")
    ax.figure.savefig("example4.svg", bbox_inches="tight")


if __name__ == "__main__":
    seaborn.set()
    example1()
    example2()
    example3()
    example4()
```

and here are the four images produced (two by `cairo` and two by `matplotlib` with `seaborn`, i.e. directly using `Curve.plot`):

![example1](https://user-images.githubusercontent.com/520669/44291737-3b7fd580-a235-11e8-8714-ff64422d15da.png)
![example2](https://user-images.githubusercontent.com/520669/44291739-3f135c80-a235-11e8-9c84-620a18cfe548.png)
![example3](https://user-images.githubusercontent.com/520669/44291741-40dd2000-a235-11e8-8d30-0d85c3b3f92a.png)
![example4](https://user-images.githubusercontent.com/520669/44291742-42a6e380-a235-11e8-9d35-70d0857427a2.png)

**Comment by stuaxo** [comment]
Wow, cheers for looking at this, I'll have a look.

**Comment by stuaxo** [comment]
I'll start having a play with the examples you left and ask here if I can't work out what's happening.
