### ISSUE TITLE
Add `project_urls` to `setup.py`

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#135]
Via https://github.com/googleapis/google-cloud-python/issues/6315.

See the [`wheel` example][1]. H/T to @tseaver for the idea.

[1]: https://github.com/pypa/wheel/blob/3d3708c659f7b9988f958539e7748a1a01ee6e77/setup.py#L37-L43

**Comment by dhermes** [comment]
Re-opening. I cut a [release][1] but project links is "as before":

![screenshot from 2018-10-30 23-36-46](https://user-images.githubusercontent.com/520669/47770455-b5542680-dc9c-11e8-9e26-c43d60eb8b56.png)

as compared to the [`wheel` PyPI page][2]:

![screenshot from 2018-10-30 23-36-41](https://user-images.githubusercontent.com/520669/47770469-bf762500-dc9c-11e8-82e7-dbf426492611.png)

[1]: https://pypi.org/project/bezier/0.9.0/
[2]: https://pypi.org/project/wheel/0.32.2/

**Comment by dhermes** [comment]
@theacodes is there some magic incantation I bungled? Or is this a secret opt-in feature?

**Comment by theacodes** [comment]
How did you upload? iirc there might be some weird bug where you *must* upload the wheel first.

**Comment by dhermes** [comment]
@theacodes I uploaded the `sdist` first. Blerg.

**Comment by dhermes** [comment]
Confirmed, it looks great [in `0.11.0`][1]:

![Screenshot from 2020-01-11 21-10-44](https://user-images.githubusercontent.com/520669/72214441-dde9ca00-34b6-11ea-9a68-9cbe7c7813ed.png)

[1]: https://pypi.org/project/bezier/0.11.0/
