### ISSUE TITLE
Curve approximation with a limited degree Bezier 

### ISSUE THREAD

**Issue by 23pointsNorth** [dhermes/bezier#136]
Hi,

I feel like I should have found this lib earlier rather than later. This should be a standard problem, but I have a set of points(N, in 2D), that come from a noisy reading from an underlying curve. I want to fit a K degree to the sequence to minimize the error in a least squares sense. 

Is there a smarter way than to fit a N degree Bezier Curve and `reduce()` it to K?

Thanks,
23pointsNorth

**Comment by dhermes** [comment]
So your `N` points **could** be used to define a degree `N - 1` curve, but how do you want to do this? 

- Do you want to use them as control points? 
- As points **on** the curve?
- A different option?

Once you've determined that, you may want to manually set up the system. E.g. you could "pretend" to do degree elevation on a curve with the identity matrix:

```python
In [1]: import bezier

In [2]: import numpy as np

In [3]: nodes = np.eye(4, order="F")

In [4]: curve = bezier.Curve.from_nodes(nodes)

In [5]: curve
Out[5]: <Curve (degree=3, dimension=4)>

In [6]: curve.elevate().nodes
Out[6]:
array([[1.  , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.75, 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.5 , 0.75, 0.  ],
       [0.  , 0.  , 0.  , 0.25, 1.  ]])
```

and the use the resulting "elevation matrix" to do a least squares solve. (If you elevate multiple times, you'd get a similar matrix.)

If you wanted to do a least squares fit of your data, you're probably better off using a degree lower than `N - 1` and then trying to fit them as parameters.

For example, if you had a quadratic with "unknown" vectors, you could "symbolically" represent them with the columns in the 3 x 3 iidentity matrix. Then if you wanted to fit the curve with `> 3` -- let's say 5 -- points, you could write them in terms of the "symbolic" control points:

```python
In [1]: import bezier

In [2]: import numpy as np

In [3]: nodes = np.eye(3, order="F")

In [4]: curve = bezier.Curve.from_nodes(nodes)

In [5]: params = np.linspace(0.0, 1.0, 5)

In [6]: params
Out[6]: array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]: evaluated = curve.evaluate_multi(params)

In [8]: evaluated
Out[8]:
array([[1.    , 0.5625, 0.25  , 0.0625, 0.    ],
       [0.    , 0.375 , 0.5   , 0.375 , 0.    ],
       [0.    , 0.0625, 0.25  , 0.5625, 1.    ]])
```

i.e. if your unknown control points are `p0`, `p1` and `p2`, this says your known points `v0`, `v1`, `v2`, `v3` and `v5` should satisfy:

```
v0 = p0
v1 = 0.5625 p0 + 0.375 p1 + 0.0625 p2
v2 = 0.25 p0 + 0.5 p1 + 0.25 p2
v3 = 0.0625 p0 + 0.375 p1 + 0.5625 p2
v4 = p2
```

And you can find a least squares solution to this system, via:

```python

In [9]: pseudo_inverse = np.linalg.solve(evaluated.dot(evaluated.T), evaluated).T

In [10]: np.round(pseudo_inverse * 35).astype(int)
Out[10]:
array([[ 31, -23,   3],
       [  9,  22,  -5],
       [ -3,  37,  -3],
       [ -5,  22,   9],
       [  3, -23,  31]])
```

i.e.

```
p0 = (31 v0 + 9 v1 - 3 v2 - 5 v3 + 3 v4) / 35
p1 = (-23 v0 + 22 v1 + 37 v2 + 22 v3 - 23 v4) / 35
p2 = (3 v0 - 5 v1 - 3 v2 + 9 v3 + 31 v4) / 35
```

PS If I were you I'd consider using SymPy to solve these systems if you aren't doing it in real time.

[1]: https://bezier.readthedocs.io/en/0.8.0/reference/bezier.curve.html#bezier.curve.Curve.reduce_

**Comment by dhermes** [comment]
@23pointsNorth did this help? Shall we continue discussion or close the issue?

**Comment by 23pointsNorth** [comment]
Hi @dhermes I got distracted as this ended up working :) 
Thanks for the help!

I will close this issue, as the question is resolved.

**Comment by dhermes** [comment]
Great to hear, cheers!
