### ISSUE TITLE
Expose evaluate_hodograph in Python public API

### ISSUE THREAD

**Issue by bmbuncher** [dhermes/bezier#138]
Hi!  I am trying to use `evaluate_hodograph` in Python 3.6, but have been having some substantial difficulty with importing it.  I have been through the documentation on binary extensions many times, but have been unable to figure this out.

I have tried `cimport bezier._curve` (as described here: https://bezier.readthedocs.io/en/0.9.0/python/pxd/index.html), but this also failed due to a syntax error (I presume due to the fact that I'm using Python instead of Cython).

In addition, I tried building from the source using `python3.6 setup.py build_ext`, which also did not work.  This was equivalent to installing via pip.

Do you know what the issue may be?  I am using the Ubuntu Bash shell native to Windows 10; thus far, I have been treating the system as an Ubuntu system when performing installations, which has worked well, so I don't think I will need to deal with DLL files.  If there is any other information I can provide, please let me know.  Thank you!

**Comment by dhermes** [comment]
@bmbuncher I'm happy to re-open the issue if this hasn't solved your problem. I filed #140 to follow up on the whole C ABI / PXD / Python API confusion.

**Comment by bmbuncher** [comment]
Hi!  My apologies for the late response; it's been a crazy week!  This did solve my issue, thank you so much!  The issue was that I was using the wrong .pxd file.

**Comment by dhermes** [comment]
Great to hear, cheers!

**Comment by anntzer** [comment]
Would you consider revisiting this and making evaluate_hodograph public python API?

**Comment by dhermes** [comment]
Sure thing, as always thanks for coming by @anntzer!
