### ISSUE TITLE
curve/curve intersection(CCI)

### ISSUE THREAD

**Issue by lens000** [dhermes/bezier#139]
# The book or paper about CCI

I am new to bezier curve about curve/cure intersection. I want to learn curve/curve intersection through your library.

I have a small request, can you introduce the book or paper about curve/curve intersection?

**Comment by dhermes** [comment]
Thanks for reaching out @lens000.

I would say the best place to start is Tom Sederberg's course text: http://tom.cs.byu.edu/~557/text/cagd.pdf (Chapter 7 is "Planar Curve Intersection").

A good paper to start with is a review paper comparing 3 algorithms https://dx.doi.org/10.1016/S0010-4485(86)80013-6.

If you want to go another route (algebraic): https://www2.eecs.berkeley.edu/Pubs/TechRpts/1992/6266.html

**Comment by dhermes** [comment]
@lens000 If this didn't answer your question I'm happy to re-open the issue.

**Comment by lens000** [comment]
@dhermes Thanks for your answer. This answer is very help for me. 
I open the http://tom.cs.byu.edu/~557/text/cagd.pdf in my browser and I found that website cannot be accessed.
I search the resource in internet and then I find same book from https://scholarsarchive.byu.edu/cgi/viewcontent.cgi?article=1000&context=facpub

**Comment by dhermes** [comment]
Sorry for the broken link, I'm happy to hear you've found a replacement
