### ISSUE TITLE
Build OS X wheels on a version older than 10.12

### ISSUE THREAD

**Issue by misaelcaloz** [dhermes/bezier#142]
This can be done via Travis, and probably should have been setup before.

----

**Original Title**: Mac os error: Symbol not found: _clock_gettime

Hi,

I work on osx 10.11. I installed bezier correctly, when I import it in python I got an errror on Symbol not found: _clock_gettime. See below. 

Sorry I'm not an expert but is it related to bezier package or to osx ?

Thanks.

```python
>>> import bezier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/misaelcaloz/anaconda/lib/python2.7/site-packages/bezier/__init__.py", line 45, in <module>
    __config__.handle_import_error(exc, "_speedup")
  File "/Users/misaelcaloz/anaconda/lib/python2.7/site-packages/bezier/__config__.py", line 72, in handle_import_error
    raise caught_exc
ImportError: dlopen(/Users/misaelcaloz/anaconda/lib/python2.7/site-packages/bezier/_speedup.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Users/misaelcaloz/anaconda/lib/python2.7/site-packages/bezier/.dylibs/libgfortran.5.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/misaelcaloz/anaconda/lib/python2.7/site-packages/bezier/.dylibs/libgfortran.5.dylib
 ```

**Comment by dhermes** [comment]
Thanks, that's great feedback! I've been building the wheels on my personal laptop and didn't realize there was such an issue. I'll look into getting an older version of OS X to build to wheels on Travis and try to understand why this problem occurs (i.e. why isn't `_clock_gettime` in earlier versions of `libSystem.B`).

**Comment by misaelcaloz** [comment]
Hi, thanks a lot for the answer, it worked straight away ! This is what I did:
I uninstalled bezier with `pip uninstall bezier`
and installed it again as you said with `python -m pip install --no-binary=bezier bezier`

Cheers

**Comment by dhermes** [comment]
Ha good call on the `pip uninstall`, my bad.

Cheers! Did you already have `gfortran` installed or did it install without the speedups? You can check via:

```python
>>> import bezier
>>> bezier.__version__
'0.9.0'
>>> bezier._HAS_SPEEDUP
True
```

**Comment by dhermes** [comment]
It seems `gfortran` wasn't detected. If you'd like the speedups (they'll speed up `bezier`, so that's a good thing), I'm happy to help you figure out why they weren't installed. When you `pip install`-ed with `--no-binary=bezier` you likely had a message printed to `stderr` explaining why they weren't built (i.e. it may not have been a missing `gfortran` but some other issue).

Otherwise, enjoy the Python-only version of `bezier`, it has the exact same features.

**Comment by dhermes** [comment]
See https://github.com/dhermes/bezier/issues/143#issuecomment-444734837. I'm electing not to support 10.11 since it is no longer officially supported by Apple.

@misaelcaloz Building from source will still work just fine. I'd be
