### ISSUE TITLE
[QUESTION] Transpose nodes to (npts, ndim) instead of (ndim, npts)

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#153]
See: 

- https://github.com/dhermes/bezier/issues/146#issuecomment-459350128

cc @anntzer

----

Some notes:

- This would be a breaking change and hence painful for users
- I **used** to have the orientation this way and switched it since Fortran order made grabbing an entire point / column at once important to happen with data locality
- The data-contiguous argument goes away if we internally use C-order (for Python mode) instead of F-order

**Comment by dhermes** [comment]
So I just don't have the bandwidth to make a change like this (especially since it'll be such a breaking change).

For anyone that comes across here, you can use `C`-ordered NumPy arrays (the default ordering in most situations) and just pass in the transpose of those arrays with `copy=False`. For example:

```python
In [1]: import bezier

In [2]: bezier.__version__
Out[2]: '2021.2.12'

In [3]: import numpy as np

In [4]: nodes_T = np.array([
   ...:     [0.0, 0.0],
   ...:     [0.5, 1.0],
   ...:     [1.0, 0.0],
   ...: ], order="C")

In [5]: curve = bezier.Curve.from_nodes(nodes_T.T, copy=False)

In [6]: curve._nodes.base is nodes_T
Out[6]: True

In [7]: curve._nodes.flags
Out[7]: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

**Comment by anntzer** [comment]
No worries, thanks for considering the proposal.
