### ISSUE TITLE
Crash when using with panda3d in python 3.8

### ISSUE THREAD

**Issue by eduardomezencio** [dhermes/bezier#186]
I have reported the same problem to panda3d, but the crash happens while importing the bezier package, so I think this may be a better place to report. It may also be a problem with python 3.8 itself since there is no problem when using python 3.7.

Using python 3.8.1, panda3d 1.10.5, bezier 2020.1.14 in arch linux.

The problem is that if I import the bezier package before I instantiate the panda3d's ShowBase object, nothing wrong happens. Importing it after causes a crash with message "malloc(): invalid size (unsorted)"

Example without error:
```
import bezier

from direct.showbase.ShowBase import ShowBase
base = ShowBase()
base.run()
```

Example with error:
```
from direct.showbase.ShowBase import ShowBase
base = ShowBase()

import bezier

base.run()
```

**Comment by dhermes** [comment]
Thanks for reporting! I'll look into it.

What operating system are you using?

**Comment by dhermes** [comment]
Tiny progress, I have successfully reproduced on Ubuntu 18.04.3 on my personal laptop and the error **did not** occur on macOS. Now to dive in a bit more.

**Comment by dhermes** [comment]
OK, I "confirmed" it's not `bezier` causing the issue. A **more** minimal repro is the following:

```python
from direct.showbase.ShowBase import ShowBase

base = ShowBase()

import hmac
```

(More about how I found this in a moment.)

**Comment by dhermes** [comment]
I made a virtual environment and installed the packages

```
python3.8 -m virtualenv .venv
.venv/bin/pip install ipython bezier panda3d
```

then ran `python repro.py` (as I modified the reproduction of the error) via `strace`

```
strace .venv/bin/python repro.py > strace-stdout.txt 2> strace-stderr.txt
```

First I started with `import bezier`, then

```python
import sys
sys.path.append(".venv/lib/python3.8/site-packages/bezier")
import _speedup
```

which showed the Python binary extension module `_speedup.so` was the culprit. From there, the `strace-stderr.txt` output always indicated something bad happened either in the import of `_hashlib` or `_blake2` (neither of which caused an issue on their own) but **one more step** back in the `strace` output pointed to

```
...
stat(".../bezier", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat(".../bezier/.venv/lib/python3.8", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat(".../bezier/.venv/lib/python3.8/hmac.py", {st_mode=S_IFREG|0644, st_size=6124, ...}) = 0
stat(".../bezier/.venv/lib/python3.8/hmac.py", {st_mode=S_IFREG|0644, st_size=6124, ...}) = 0
openat(AT_FDCWD, ".../bezier/.venv/lib/python3.8/__pycache__/hmac.cpython-38.pyc", O_RDONLY|O_CLOEXEC) = 27
fstat(27, {st_mode=S_IFREG|0644, st_size=5910, ...}) = 0
ioctl(27, TCGETS, 0x7ffd2fe22710)       = -1 ENOTTY (Inappropriate ioctl for device)
lseek(27, 0, SEEK_CUR)                  = 0
lseek(27, 0, SEEK_CUR)                  = 0
...
```

**Comment by dhermes** [comment]
@eduardomezencio Thanks for filing and sorry I couldn't help narrow in on where the breakage is. You **can** install `bezier` **without** the speedup via

```
$ BEZIER_NO_EXTENSION=true \
>   python  -m pip install --upgrade bezier --no-binary=bezier
```

however in my testing this didn't solve the problem.

**Comment by eduardomezencio** [comment]
Thank you for your efforts! I will share this more minimal example with the panda3d developers, now that panda3d is the only package needed to reproduce the error.

**Comment by dhermes** [comment]
> However in my testing this didn't solve the problem.

AFAICT that's because the `hmac` import is happening via `import numpy as np`, so any dependency using `numpy` will hit this. I noticed I could get the error to change if I removed `__pycache__` first:

```
$ python3.8 -m virtualenv .venv
$ .venv/bin/pip install panda3d
$ .venv/bin/pip freeze
panda3d==1.10.5
$
$ .venv/bin/python -c 'import direct.showbase.ShowBase as dss; base = dss.ShowBase(); import hmac'
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
malloc(): memory corruption
Aborted (core dumped)
$
$ rm -fr .venv/lib/python3.8/__pycache__/
$ .venv/bin/python -c 'import direct.showbase.ShowBase as dss; base = dss.ShowBase(); import hmac'
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
free(): invalid pointer
Aborted (core dumped)
$
$ rm -fr $(find .venv/ -name __pycache__ -type d)
$ .venv/bin/python -c 'import direct.showbase.ShowBase as dss; base = dss.ShowBase(); import hmac'
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Segmentation fault (core dumped)
```

I am having fun tracking down this issue and have narrowed it down to a [block][1] in `hashlib.py`. Can you link me to the issue on the `panda3d` issue tracker?

[1]: https://github.com/python/cpython/blob/v3.8.1/Lib/hashlib.py#L247-L254

**Comment by dhermes** [comment]
OK, even better, I have traced it to [this line][1]. Executing any of the five names that hit that line will cause a segfault

```python
import _hashlib


_hashlib.openssl_md5()  # <-- free(): corrupted unsorted chunks
_hashlib.openssl_sha1()  # <-- free(): corrupted unsorted chunks
_hashlib.openssl_sha224()  # <-- free(): corrupted unsorted chunks
_hashlib.openssl_sha256()  # <-- free(): corrupted unsorted chunks
_hashlib.openssl_sha384()  # <-- No message
```

[1]: https://github.com/python/cpython/blob/v3.8.1/Lib/hashlib.py#L131
