### ISSUE TITLE
PyPI Windows wheel installs unimportable package

### ISSUE THREAD

**Issue by anntzer** [dhermes/bezier#206]
After pip-installing bezier from PyPI on Windows, the package cannot be imported:
```
~> python -c "import bezier"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\Miniconda3\envs\default\lib\site-packages\bezier\__init__.py", line 44, in <module>     
    __config__.handle_import_error(exc, "_speedup")
  File "...\Miniconda3\envs\default\lib\site-packages\bezier\__config__.py", line 92, in handle_impo
rt_error
    raise caught_exc
  File "...\Miniconda3\envs\default\lib\site-packages\bezier\__init__.py", line 40, in <module>     
    import bezier._speedup  # noqa: F401
ImportError: DLL load failed while importing _speedup: The specified module could not be found.
```

This is in a Py3.8 conda env.

**Comment by dhermes** [comment]
Appreciate the report. Which version of `bezier`? (I assume `2020.2.3`)

**Comment by anntzer** [comment]
yes, the latest.

**Comment by dhermes** [comment]
I was able to reproduce as well. Thanks for pointing out, it is [this line][1]

```python
extra_dll_dir = pkg_resources.resource_filename("bezier", "extra-dll")
```

In `conda`, this causes a failure because it tries to **import** `bezier` while locating it (this indicates to me that the `conda`-supplied `setuptools` is different):

```
Python 3.8.1 | packaged by conda-forge | (default, Jan 29 2020, 14:24:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.resource_filename("bezier", "extra-dll")
Traceback (most recent call last):
  File "C:\Users\dhermes\Anaconda3\envs\issue-206\lib\site-packages\pkg_resources\__init__.py", line 360, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'bezier'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dhermes\Anaconda3\envs\issue-206\lib\site-packages\pkg_resources\__init__.py", line 1145, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "C:\Users\dhermes\Anaconda3\envs\issue-206\lib\site-packages\pkg_resources\__init__.py", line 362, in get_provider
    __import__(moduleOrReq)
  File "C:\Users\dhermes\Anaconda3\envs\issue-206\lib\site-packages\bezier\__init__.py", line 44, in <module>
    __config__.handle_import_error(exc, "_speedup")
  File "C:\Users\dhermes\Anaconda3\envs\issue-206\lib\site-packages\bezier\__config__.py", line 92, in handle_import_error
    raise caught_exc
  File "C:\Users\dhermes\Anaconda3\envs\issue-206\lib\site-packages\bezier\__init__.py", line 40, in <module>
    import bezier._speedup  # noqa: F401
ImportError: DLL load failed while importing _speedup: The specified module could not be found.
```

In CPython (i.e. not `conda`) this does not error out

```
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.resource_filename("bezier", "extra-dll")
'C:\\Users\\dhermes\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\bezier\\extra-dll'
```

----

I have been hearing recently that `pkg_resources` should be avoided and instead `importlib.resources` (from the standard library) should be used. I expected to be able to fix it with

```python
with importlib.resources.path("bezier", "extra-dll") as extra_dll_dir:
    return extra_dll_dir
```

but (1) this fails for the same reasons in `conda` and (2) `importlib.resources` doesn't exist in Python 3.6 which `bezier` still supports.

----

I may go [this route][2]:

```python
import distutils.sysconfig
import pathlib

site_packages_lib = distutils.sysconfig.get_python_lib()
extra_dll_dir = pathlib.Path(site_packages_lib) / "bezier" / "extra-dll"
```

but I'm a bit worried that I actually need to loop through every single directory in `sys.path` (`distutils.sysconfig.get_python_lib()` is just one of them). For example (on my current Linux install, not Windows):

```python
>>> import distutils.sysconfig
>>> import sys
>>> distutils.sysconfig.get_python_lib() in sys.path
True
>>> distutils.sysconfig.get_python_lib()
'/home/dhermes/.pyenv/versions/3.8.0/lib/python3.8/site-packages'
>>> for p in sys.path: print(repr(p))
... 
''
'/home/dhermes/.pyenv/versions/3.8.0/lib/python38.zip'
'/home/dhermes/.pyenv/versions/3.8.0/lib/python3.8'
'/home/dhermes/.pyenv/versions/3.8.0/lib/python3.8/lib-dynload'
'/home/dhermes/.local/lib/python3.8/site-packages'
'/home/dhermes/.pyenv/versions/3.8.0/lib/python3.8/site-packages'
```

[1]: https://github.com/dhermes/bezier/blob/2020.2.3/src/python/bezier/__config__.py#L62
[2]: https://stackoverflow.com/a/122340/1068170

**Comment by dhermes** [comment]
@anntzer 

1.  Thanks a lot for filing (this and every other issue you've filed)
1.  Do you have any suggestions for where to report this `pkg_resources` / `importlib` "regression" within the `conda` ecosystem?
1.  If you want this to work today, you can do the following "magic dance" before importing `bezier`
    ```python
    import distutils.sysconfig
    import os
    import pathlib
    
    site_packages_lib = distutils.sysconfig.get_python_lib()
    extra_dll_dir = pathlib.Path(site_packages_lib) / "bezier" / "extra-dll"
    os.add_dll_directory(extra_dll_dir)
    
    import bezier
    ```
1.  Once I come up with a fix that I'm happy with, I'll probably do a `2020.3.x` release (i.e. it probably won't happen until March, but hopefully soon)
1.  I can probably add a `conda` check to the [`bezier-wheels` acceptance tests][1] to prevent this from happening in the future

[1]: https://github.com/dhermes/bezier-wheels/blob/db2fb9b39aa8575953a67e63074862aaec069d81/.appveyor.yml#L106

**Comment by anntzer** [comment]
> Thanks a lot for filing (this and every other issue you've filed)

Thanks for making bezier available :) it's great!

> Do you have any suggestions for where to report this pkg_resources / importlib "regression" within the conda ecosystem?

Nothing particularly smart, probably just to the main conda repo?

> If you want this to work today, you can do the following "magic dance" before importing bezier
import distutils.sysconfig
import os
import pathlib
site_packages_lib = distutils.sysconfig.get_python_lib()
extra_dll_dir = pathlib.Path(site_packages_lib) / "bezier" / "extra-dll"
os.add_dll_directory(extra_dll_dir)
import bezier

Thanks.

> Once I come up with a fix that I'm happy with, I'll probably do a 2020.3.x release (i.e. it probably won't happen until March, but hopefully soon)

No hurries.

> I can probably add a conda check to the bezier-wheels acceptance tests to prevent this from happening in the future

Maybe a good idea?

-----

Alternatively, the following seems to work
```
importlib.metadata.files("bezier")[-1].locate()
```
Actually it's not the last one, you need to search in the list for the right file but you get the idea.
There's a backport of importlib.metadata (as importlib_metadata) available on PyPI, you could just add that as conditional dep on Py<3.8 on Windows.
This will in the rather obscure case of the module being imported from a zip (or egg) because then importlib.resources also takes care of the unzipping and putting the dll in a temporary dir, but I doubt this is a common case, and if anything you can always check whether the file returned by importlib.metadata really exists and if not try to fallback to pkg_resources/importlib.resources, so you'd only fail on conda+importing from a zip.

**Comment by dhermes** [comment]
SG, experimenting with this (on macOS right now), seems promising:

```
In [1]: import sys                                                                                                                                                                                               

In [2]: "bezier" in sys.modules                                                                                                                                                                                  
Out[2]: False

In [3]: import importlib.metadata                                                                                                                                                                                

In [4]: bezier_files = importlib.metadata.files("bezier")                                                                                                                                                        

In [5]: "bezier" in sys.modules                                                                                                                                                                                  
Out[5]: False

In [6]: bezier_files                                                                                                                                                                                             
Out[6]: 
[PackagePath('bezier-2020.2.3.dist-info/INSTALLER'),
 PackagePath('bezier-2020.2.3.dist-info/LICENSE'),
...
```

I'll check it out on a Windows machine (with `conda`) tonight hopefully.

**Comment by dhermes** [comment]
OK got Windows access much sooner, verified that `importlib.metadata.files` doesn't cause an error by attempting to import the module. However, I realize that the output is a set of relative paths, which still means I have to guess what the path is relative to (making it the same as just jumping right to `site-packages/lib`)
