### ISSUE TITLE
Update README.md with all imports per example, so they can be copy-pasted?

### ISSUE THREAD

**Issue by Pomax** [dhermes/bezier#210]
Right now the examples do not show which packages need to be imported, so while it is reasonable to guess what `np` is, for example, not everyone will have heard of numpy yet, and even if they have, they might not know that `np` is a common abbreviation for it - it's better to include all the import statements in the examples (including the `import bezier` one).

**Comment by dhermes** [comment]
Hey I know you! Thanks for the awesome https://github.com/Pomax/bezierjs and http://pomax.github.io/bezierjs/!

**Comment by Pomax** [comment]
hah, always fun to meet someone who's seen my work =)

**Comment by dhermes** [comment]
@Pomax I may try to tackle this soon, but not really sure how to go about it. I want to **minimize** imports (without hitting the minimum of 0) by just including them once per docs page.

For example https://bezier.readthedocs.io/en/2021.2.12/ just jumps right in with `np.asfortranarray()` and `bezier.Curve()`, so I'll be able to update those with two imports of `numpy as np` and `bezier` first. Just not sure how to be comprehensive and find all my docs pages.

**Comment by dhermes** [comment]
As of 6164b403b7e4bb956a4d2518bedef98e70a53641, here is the list of (59) files for me to go through

- [ ] abi/curve.html
- [ ] abi/curve_intersection.html
- [ ] abi/helpers.html
- [ ] abi/index.html
- [ ] abi/installation.html
- [ ] abi/status.html
- [ ] abi/triangle.html
- [ ] abi/triangle_intersection.html
- [ ] algorithms/curve-curve-intersection.html
- [ ] algorithms/geometric-curve-intersection.html
- [ ] algorithms/index.html
- [ ] development.html
- [ ] index.html
- [ ] python/binary-extension.html
- [ ] python/index.html
- [ ] python/pxd/curve.html
- [ ] python/pxd/curve_intersection.html
- [ ] python/pxd/helpers.html
- [ ] python/pxd/index.html
- [ ] python/pxd/status.html
- [ ] python/pxd/triangle.html
- [ ] python/pxd/triangle_intersection.html
- [ ] python/reference/bezier.curve.html
- [ ] python/reference/bezier.curved_polygon.html
- [ ] python/reference/bezier.hazmat.algebraic_intersection.html
- [ ] python/reference/bezier.hazmat.clipping.html
- [ ] python/reference/bezier.hazmat.curve_helpers.html
- [ ] python/reference/bezier.hazmat.geometric_intersection.html
- [ ] python/reference/bezier.hazmat.helpers.html
- [ ] python/reference/bezier.hazmat.html
- [ ] python/reference/bezier.hazmat.intersection_helpers.html
- [ ] python/reference/bezier.hazmat.triangle_helpers.html
- [ ] python/reference/bezier.hazmat.triangle_intersection.html
- [ ] python/reference/bezier.html
- [ ] python/reference/bezier.triangle.html
- [ ] releases/0.0.1.html
- [ ] releases/0.1.0.html
- [ ] releases/0.1.1.html
- [ ] releases/0.10.0.html
- [ ] releases/0.11.0.html
- [ ] releases/0.2.0.html
- [ ] releases/0.2.1.html
- [ ] releases/0.3.0.html
- [ ] releases/0.4.0.html
- [ ] releases/0.5.0.html
- [ ] releases/0.6.0.html
- [ ] releases/0.6.1.html
- [ ] releases/0.6.2.html
- [ ] releases/0.6.3.html
- [ ] releases/0.6.4.html
- [ ] releases/0.7.0.html
- [ ] releases/0.8.0.html
- [ ] releases/0.9.0.html
- [ ] releases/2020.1.14.html
- [ ] releases/2020.2.3.html
- [ ] releases/2020.5.19.html
- [ ] releases/2021.2.12.html
- [ ] releases/index.html
- [ ] releases/latest.html
