### ISSUE TITLE
need for a tutorial about use of the package to draw a bezier curve

### ISSUE THREAD

**Issue by piscvau** [dhermes/bezier#213]
PILLOW package does not provide any primitive to draw Bezier curve. I suspect your package brings a solution. If it is appropriate to use this package, a tutorial  would be appropriate.It is difficult for  a non mathematician, to get into you package!........

**Comment by dhermes** [comment]
@piscvau Thanks a lot for stopping by and giving feedback. Did you happen to see the "Getting Started" section of the docs? https://bezier.readthedocs.io/en/2020.2.3/#getting-started

It's certainly not comprehensive but at least shows how to create a curve and plot it.

**Comment by dhermes** [comment]
As far as what [`pillow`][1] provides, this will be a bit different especially if you've never used `matplotlib`. The plotting support is directed at the scientific Python ecosystem where `matplotlib` and related tools are common. This is somewhat different than `pillow` where an image is just a rectangular array of pixel data that you can manipulate.

It **is** [possible][2] to convert a `matplotlib` "axis" directly into a `pillow` Image:

```python
>>> import copy
>>> import io
>>>
>>> import bezier
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> import PIL.Image
>>>
>>> nodes = np.asfortranarray([
...     [0.0, 0.5, 1.0],
...     [0.0, 1.0, 0.0],
... ])
>>> curve = bezier.Curve(nodes, degree=2)
>>>
>>> figure = plt.figure()
>>> _ = curve.plot(num_pts=256, ax=figure.gca())
>>> buffer = io.BytesIO()
>>> figure.savefig(buffer, format="png")
>>> buffer.seek(0)
>>> img = copy.deepcopy(PIL.Image.open(buffer))
>>> buffer.close()
```

[1]: https://pillow.readthedocs.io/en/stable/
[2]: https://stackoverflow.com/q/57316491/1068170

**Comment by dhermes** [comment]
I'm closing in hopes that I've answered the question sufficiently.
