### ISSUE TITLE
split bezier curve at t

### ISSUE THREAD

**Issue by mok33** [dhermes/bezier#230]
I can't seem to find any way to cut a bezier curve into two pieces at t. 
Is there any way to do this ?

Thanks.

**Comment by dhermes** [comment]
You can use [`Curve.specialize()`][1] for this:

```python
In [1]: import numpy as np

In [2]: nodes = np.asfortranarray([
   ...:     [0.0, 1.25, 2.0],
   ...:     [0.0, 3.0 , 1.0],
   ...: ])

In [3]: import bezier

In [4]: curve = bezier.Curve.from_nodes(nodes)

In [5]: t = 0.375

In [6]: left = curve.specialize(0.0, t)

In [7]: right = curve.specialize(t, 1.0)
```

To see these:

```python
In [8]: import matplotlib.pyplot as plt

In [9]: import seaborn

In [10]: seaborn.set()

In [11]: _, axes = plt.subplots(1, 3, sharex=True, sharey=True)

In [12]: axes = axes.flatten()

In [13]: _ = curve.plot(256, ax=axes[0])

In [14]: _ = left.plot(256, ax=axes[1])

In [15]: _ = right.plot(256, ax=axes[2])

In [16]: for ax in axes:
    ...:     ax.axis("scaled")
    ...:

In [17]: plt.savefig("issue-230.png", dpi=300, bbox_inches="tight")
```

![issue-230](https://user-images.githubusercontent.com/520669/84537475-ae78fc80-aca4-11ea-8757-5ffcca8c3649.png)

----

I'm pre-emptively closing this issue because I think this answer should work. Let me know if you have other questions and I'm happy to re-open if I've closed the issue prematurely.

[1]: https://bezier.readthedocs.io/en/2020.5.19/python/reference/bezier.curve.html#bezier.curve.Curve.specialize

**Comment by ariejdl** [comment]
Hi @dhermes thank you for this sophisticated and useful library.  Following your example above and adding these two lines I don't understand how the proportion `t` is used, it doesn't seem to represent the length along the curve.  Sorry if I'm being ignorant of something here

```
print(curve.length, curve.length * t, curve.length * (1 - t))
print(left.length + right.length, left.length, right.length)
```

The lengths are not equal:
```
3.4231293202530964 1.2836734950949111 2.139455825158185
3.4231293202530977 1.781484083077751 1.6416452371753467
```

**Comment by dhermes** [comment]
So `curve.length` and `left.length + right.length` are equal to machine precision:

```python
In [18]: curve.length
Out[18]: 3.4231293202530964

In [19]: left.length + right.length
Out[19]: 3.4231293202530977

In [20]: curve.length.hex()
Out[20]: '0x1.b6291a003b9e0p+1'

In [21]: (left.length + right.length).hex()
Out[21]: '0x1.b6291a003b9e3p+1'
```

As we can see from the hex representations they differ in 3 [ULPs][1]:

```python
In [22]: difference = (left.length + right.length) - curve.length

In [23]: difference / np.spacing(curve.length)
Out[23]: 3.0
```

As for the ratios `left.length / curve.length` and `right.length / curve.length`, these are not expected to match the ratios `t` and `(1 - t)`. The input `t` is in the **parameter** space, but in the actual space the curve lives, the length is essentially a **polynomial** function of the parameter, not a linear function.

----

Now I'd like to answer **why** `left.length + right.length` is not identically equal to `curve.length`. The design of `Curve.specialize()` is intended to get the most accurate (to machine precision) control points for the curve that results when restricting the parameter space. Every other quantity or procedure (length, evaluation, hodograph, intersect, point location) uses these new control points.

Even if the library was trying to optimize for the sum of the length being equal (which it isn't) this may be impossible in finite precision. We need to choose **some** set of control points for each segment of the curve and there may not exist a set of control points to actually get exact matching.

----

Do let me know if there is anything else unclear. I am going to preemptively close this issue in the hopes I've addressed the question.

[1]: https://en.wikipedia.org/wiki/Unit_in_the_last_place

**Comment by ariejdl** [comment]
Thanks @dhermes sorry it wasn't clear, my point was not about precision but rather about ratios as you refer to, is there a way to map between parameter space (the polynomial function) and the length of the line space, in order to have a way of using the ratio along the length of the line? Maybe this is a function that could be added to the library.

**Comment by dhermes** [comment]
In general it's not easy to do, for a 2D curve the length is given by `L(t) = Integral_0^t sqrt((x')^2 + (y')^2) ds`:

![Screenshot 2022-11-05 at 2 22 49 PM](https://user-images.githubusercontent.com/520669/200137389-3c229966-8765-479f-9313-48e8b4d7cd70.png)

For this curve we've been discussing we have:

```python
In [24]: import sympy

In [25]: s = sympy.Symbol("s")

In [26]: xs, ys = curve.to_symbolic()

In [27]: xs
Out[27]: -s*(s - 5)/2

In [28]: ys
Out[28]: -s*(5*s - 6)

In [29]: (xs.diff(s)**2 + ys.diff(s)**2).factor()
Out[29]: (404*s**2 - 500*s + 169)/4
```

A quick check against Wolfram Alpha shows a gnarly function (and you want to **invert** this function, so it gets even worse):

![Screenshot 2022-11-05 at 2 28 24 PM](https://user-images.githubusercontent.com/520669/200137612-d6814c3c-e362-4e6d-94e7-c272392b2c78.png)

----

There do exist parametric curves that are parameterized in a way that respects length (or even is 1:1 equal to the length) but this library only supports **polynomial** (not **rational**) Bézier curves and they do not possess that property.

**Comment by dhermes** [comment]
Adding on to this a bit more, if you wanted to do this **numerically** it's not as bad, you can use Newton's method and just do something like this:

```python
In [30]: import scipy.optimize

In [31]: def make_objective_function(curve, t):
    ...:     length = curve.length
    ...:     desired_length = t * length
    ...: 
    ...:     def objective_function(s):
    ...:         specialized = curve.specialize(0.0, s)
    ...:         return desired_length - specialized.length
    ...: 
    ...:     return objective_function
    ...: 

In [32]: objective_function = make_objective_function(curve, 0.375)

In [33]: scipy.optimize.newton(objective_function, 0.5)
Out[33]: 0.23916557915602574
```

**Comment by ariejdl** [comment]
Thank you very much @dhermes that's very good of you to show an optimisation solution, I admire your mathematical skill!
