### ISSUE TITLE
PyInstaller bundles PyQt libraries: Incompatible Open Source Licenses

### ISSUE THREAD

**Issue by Pebaz** [dhermes/bezier#238]
Issue: [PyInstaller](https://www.pyinstaller.org/) produces an executable properly but also bundles PyQt libraries which use a license that I do not want to use.

The issue happens when you run PyInstaller on a Python file that imports the Bezier library.

Steps to reproduce:

```bash
$ cat example.py
import bezier
$ pyinstaller example.py
$ ls build/example
...
Qt5Core.dll
...
```

> *How do I restrict the dependencies that Bezier uses so that one of them does not import PyQ5?*

**Comment by dhermes** [comment]
It's not coming from `bezier` directly:

```
$ cat bezier-requirements.txt.in 
bezier==2020.5.19
$ pip-compile --output-file bezier-requirements.txt bezier-requirements.txt.in
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file=bezier-requirements.txt bezier-requirements.txt.in
#
bezier==2020.5.19         # via -r bezier-requirements.txt.in
numpy==1.19.1             # via bezier
```

or from installing with the `full` extra

```
$ cat bezier-full-requirements.txt.in 
bezier[full]==2020.5.19
$ pip-compile --output-file bezier-full-requirements.txt bezier-full-requirements.txt.in
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file=bezier-full-requirements.txt bezier-full-requirements.txt.in
#
bezier[full]==2020.5.19   # via -r bezier-full-requirements.txt.in
cycler==0.10.0            # via matplotlib
kiwisolver==1.2.0         # via matplotlib
matplotlib==3.3.0         # via bezier
mpmath==1.1.0             # via sympy
numpy==1.19.1             # via bezier, matplotlib, scipy
pillow==7.2.0             # via matplotlib
pyparsing==2.4.7          # via matplotlib
python-dateutil==2.8.1    # via matplotlib
scipy==1.5.2              # via bezier
six==1.15.0               # via cycler, python-dateutil
sympy==1.6.1              # via bezier
```

I'm sorry I don't know much about PyInstaller. What platform is this on? The presence of PyQt5 is almost certainly due to `matplotlib`.

**Comment by dhermes** [comment]
I'm going to close this out since `bezier` doesn't directly import nor indirectly depend on PyQt5. I'm happy to re-open if you'd like or if you think I should be trying to fix something specific.

Also feel free to keep commenting here I'm happy to help troubleshoot within the greater ecosystem outside of `bezier`.

**Comment by Pebaz** [comment]
@dhermes Thank you so much for this thorough analysis. I really appreciate you taking the time to look into this.

I believe that you have definitely found the issue: matplotlib.

I will look into if that is the reason this is being bundled with bezier.

PyInstaller is a brilliant CLI program for Python that allows you to package your Python app in a freestanding binary for Windows, MacOS, and Linux! I've used pretty much all the alternatives for packaging into an executable but PyInstaller is by far the best.

Thanks again for looking into this and have a great week!
