### ISSUE TITLE
No binary wheels are available for Python 3.9

### ISSUE THREAD

**Issue by abey79** [dhermes/bezier#245]
No binary wheels are available for Python 3.9. This makes this library difficult to use as a dependency for project aimed at non-technical users. This is further complicated by the fact that Python 3.9.1 is the only version that officially supports macOS Big Sur.

**Comment by dhermes** [comment]
@abey79 Yes this is a priority for me but this project is not part of my fulltime job so I haven't had an opportunity to do it yet. I started the process last night but it will take several more hours of dedicated focus time for me to be able to finish a new release.

**Comment by abey79** [comment]
Good to hear @dhermes  👍🏻 Let me know if there is anything I can help with.

**Comment by abey79** [comment]
@dhermes is there any tips you can give to install from source? I got the following error:

```
ERROR: Command errored out with exit status 1:
     command: /private/tmp/venv39/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c3/ndnd31jn7bsf4v7j060g2ks40000gn/T/pip-install-r7qdp54c/bezier/setup.py'"'"'; __file__='"'"'/private/var/folders/c3/ndnd31jn7bsf4v7j060g2ks40000gn/T/pip-install-r7qdp54c/bezier/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c3/ndnd31jn7bsf4v7j060g2ks40000gn/T/pip-pip-egg-info-mwuhs47p
         cwd: /private/var/folders/c3/ndnd31jn7bsf4v7j060g2ks40000gn/T/pip-install-r7qdp54c/bezier/
    Complete output (1 lines):
    The BEZIER_INSTALL_PREFIX environment variable must be set.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dhermes** [comment]
@abey79 You can also build from source to get the nice speedups if you want. Requires having `gfortan` and `cmake` on your system (maybe some other libraries too, e.g. a LAPACK implementation).

You can follow https://bezier.readthedocs.io/en/2020.5.19/abi/installation.html to build `libbezier` **somewhere** (you can avoid doing it system-wide / putting it under `/usr/...`). E.g. you could decide on `INSTALL_PREFIX="$(pwd)/libbezier-release/usr"` (I would check out the `2020.5.19` tag before doing this)

Then to install with this custom `libbezier` (via https://bezier.readthedocs.io/en/2020.5.19/development.html#building-compiling)

```
BEZIER_INSTALL_PREFIX="$(pwd)/libbezier-release/usr" python -m pip install bezier==2020.5.19 --no-binary=bezier
```

**Comment by dhermes** [comment]
Making progress towards this with #246. Next big hurdle for me is building the wheels (I haven't touched the scripts / tooling since May 2020).

**Comment by dhermes** [comment]
I have now cut `2021.2.12` (I started it yesterday and forgot to increment the day, whoops).

I am going to build wheels now and get these published to PyPI.

**Comment by dhermes** [comment]
OK, all wheels are released. I ended up getting "stuck" in this process because of the `travis-ci.org` sunsetting. But luckily GitHub Actions aren't too painful to use.

**Comment by abey79** [comment]
Awesome! Thanks for the good work!
