### ISSUE TITLE
Support for PyInstaller on Windows

### ISSUE THREAD

**Issue by thorhunter1** [dhermes/bezier#254]
Hi @dhermes,

I was wondering if package was tested with pyinstaller on Windows platform as I am running into several issues.

First off, I was trying to use pip distribution package `bezier-2021.2.12-cp38-cp38-win_amd64.whl` which works fine for my project as long as I'm not using pyinstaller. After bundling, I get the following error:

```
  File "c:\users\grzegorz\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\bezier\__init__.py", line 41, in <module>
  File "site-packages\bezier\__config__.py", line 136, in handle_import_error
  File "site-packages\bezier\__init__.py", line 37, in <module>
ImportError: DLL load failed while importing _speedup: Module to found.
```

So I've noticed #237 and followed the instructions, however after trying to build bezier using:
```python -m pip install bezier --no-binary=bezier```
The result build has the following problem (note I'm running prebundled app without pyinstaller involved):
```
<module>
    from bezier import Curve
  File "C:\Users\Grzegorz\AppData\Local\Programs\Python\Python38\lib\site-packages\bezier\__init__.py", line 29, in <module>
    from bezier import __config__
  File "C:\Users\Grzegorz\AppData\Local\Programs\Python\Python38\lib\site-packages\bezier\__config__.py", line 139, in <module>
    modify_path()
  File "C:\Users\Grzegorz\AppData\Local\Programs\Python\Python38\lib\site-packages\bezier\__config__.py", line 109, in modify_path
    extra_dll_dir = _get_extra_dll_dir(bezier_files)
  File "C:\Users\Grzegorz\AppData\Local\Programs\Python\Python38\lib\site-packages\bezier\__config__.py", line 84, in _get_extra_dll_dir
    raise ImportError("No DLL directory found", bezier_files)
ImportError: ('No DLL directory found', [PackagePath('LICENSE'), PackagePath('MANIFEST.in'), PackagePath('README.rst'), PackagePath('setup.cfg'), PackagePath('setup.py'), PackagePath('src/python/bezier/__config__.py'), PackagePath('src/python/bezier/__init__.py'), PackagePath('src/python/bezier/_base.py'), PackagePath('src/python/bezier/_curve.pxd'), PackagePath('src/python/bezier/_curve_helpers.py'), PackagePath('src/python/bezier/_curve_intersection.pxd'), PackagePath('src/python/bezier/_geometric_intersection.py'), PackagePath('src/python/bezier/_helpers.pxd'), PackagePath('src/python/bezier/_helpers.py'), PackagePath('src/python/bezier/_intersection_helpers.py'), PackagePath('src/python/bezier/_legacy.py'), PackagePath('src/python/bezier/_plot_helpers.py'), PackagePath('src/python/bezier/_speedup.c'), PackagePath('src/python/bezier/_status.pxd'), PackagePath('src/python/bezier/_symbolic.py'), PackagePath('src/python/bezier/_triangle.pxd'), PackagePath('src/python/bezier/_triangle_helpers.py'), PackagePath('src/python/bezier/_triangle_intersection.pxd'), PackagePath('src/python/bezier/_triangle_intersection.py'), PackagePath('src/python/bezier/curve.py'), PackagePath('src/python/bezier/curved_polygon.py'), PackagePath('src/python/bezier/triangle.py'), PackagePath('src/python/bezier.egg-info/PKG-INFO'), PackagePath('src/python/bezier.egg-info/SOURCES.txt'), PackagePath('src/python/bezier.egg-info/dependency_links.txt'), PackagePath('src/python/bezier.egg-info/requires.txt'), PackagePath('src/python/bezier.egg-info/top_level.txt'), PackagePath('src/python/bezier.egg-info/zip-safe'), PackagePath('src/python/bezier/hazmat/__init__.py'), PackagePath('src/python/bezier/hazmat/algebraic_intersection.py'), PackagePath('src/python/bezier/hazmat/clipping.py'), PackagePath('src/python/bezier/hazmat/curve_helpers.py'), PackagePath('src/python/bezier/hazmat/geometric_intersection.py'), PackagePath('src/python/bezier/hazmat/helpers.py'), PackagePath('src/python/bezier/hazmat/intersection_helpers.py'), PackagePath('src/python/bezier/hazmat/triangle_helpers.py'), PackagePath('src/python/bezier/hazmat/triangle_intersection.py')])
```

Note that I have no problems with bundling bezier with pyinstaller on my Mac. Any help is much appreciated.

Best regards

**Comment by dhermes** [comment]
I want to make sure that you've captured the `BEZIER_NO_EXTENSION=true` from there (https://github.com/dhermes/bezier/issues/237#issuecomment-651317889). By using `--no-binary=bezier` you're telling `pip` to install from source (the "binary" referenced there is the `.whl` / wheel files). However, by default when installing from source it'll try to reference the `BEZIER_INSTALL_PREFIX`.

Anyhow, this does indeed seem like a bug in "Python-only" installs for Windows. I.e. the `_get_extra_dll_dir()` [function][1] assumes that you're always going to have a `libbezier` DLL around.

> package was tested with pyinstaller on Windows platform

No. I don't know much about pyinstaller but I am pretty sure it has a way to support DLLs and binary extensions (`.pyd` files). The thing that may be going awry with pyinstaller is the filesystem layout (I believe it creates a zip or something similar).

[1]: https://github.com/dhermes/bezier/blob/2a5ee77ba4b3cc874f87048f678b7a398985433a/src/python/bezier/__config__.py#L64

**Comment by dhermes** [comment]
@thorhunter1 so I fixed this in #255, but I don't think I'll have time to do a release in the near future (but I'll try to remember to post in this issue if I do a release).

I am still curious what the filesystem API looks like inside of PyInstaller; I am fairly certain it's possible for you to get the binary `extra-dll` packaged in there (and available) but I'm not 100% sure.

**Comment by dhermes** [comment]
https://pyinstaller.readthedocs.io/en/stable/runtime-information.html

**Comment by dhermes** [comment]
#307 relates here as well
