### ISSUE TITLE
evaluate_hodograph(s)

### ISSUE THREAD

**Issue by sunnymints** [dhermes/bezier#266]
what is meaning about the Returns of [this function][1]？
The demo：

```python
nodes = np.asfortranarray([
    [0.0, 0.625, 1.0],
    [0.0, 0.5  , 0.5],
])
curve = bezier.Curve(nodes, degree=2)
curve.evaluate_hodograph(0.75)
array([[0.875],
       [0.25 ]])
```

why the `array [[0.875], [0.25 ]` can  expression The tangent vector which  along the curve？？ 
`array([[0.875], [0.25 ]])`  are values of x-y？

[1]: https://bezier.readthedocs.io/en/2021.2.12/python/reference/bezier.curve.html#bezier.curve.Curve.evaluate_hodograph

**Comment by dhermes** [comment]
Yes, the curve given there is 2-dimensional

```python
In [1]: import bezier
  
In [2]: import numpy as np

In [3]: nodes = np.asfortranarray([
   ...:     [0.0, 0.625, 1.0],
   ...:     [0.0, 0.5  , 0.5],
   ...: ])

In [4]: curve = bezier.Curve(nodes, degree=2)

In [5]: Bs = curve.to_symbolic()

In [6]: Bs
Out[6]: 
Matrix([
[-s*(s - 5)/4],
[-s*(s - 2)/2]])
```

i.e. it has `x(s) = -s(s - 5)/4 = -s^2/4 + 5s/4` and `y(s) = -s(s - 2)/2 = -s^2/2 + s`. This means that the "hodograph" curve (i.e. `B'(s)`) is given by components

```
x'(s) = 5/4 - s/2
y'(s) = 1 - s
```

plugging in `s = 0.75 = 3/4` as in the example, we see that `B'(3/4) = [7/8, 1/4] = [0.875, 0.25]`.

----

I'm going to pre-emptively close this out as I think I have answered the question. Do let me know if there is anything unclear and I'm happy to re-open the issue.
