### ISSUE TITLE
Cut a release after adding Python 3.10 support

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#273]
~~Blocked on #270.~~

**Comment by Darylgolden** [comment]
Hi, are you planning to cut a release soon? We would love to use your library in [Manim](https://github.com/ManimCommunity/manim) :)

**Comment by dhermes** [comment]
@Darylgolden I'll try to prioritize it. I was hoping to get M1 access so I could get ARM-compatible wheels in the next release, but it doesn't seem so likely right now.

**Comment by Darylgolden** [comment]
Apologies if you've already looked into it, but have you looked at [AWS's free credits for open source projects](https://pages.awscloud.com/AWS-Credits-for-Open-Source-Projects)? I believe they have M1 macs you can use.

**Comment by dhermes** [comment]
@Darylgolden I actually hadn't. But I did click your link and it's too onerous. There are **TWO** programs to join (one for open source credits and one for M1). The open source one asks for a "Please provide the URL to your pricing estimate summary" which is just more busy work than I have time for. The M1 form (https://pages.awscloud.com/M1MacPreview.html) is luckily less onerous.

**Comment by dhermes** [comment]
This is resolved! I just released https://pypi.org/project/bezier/2023.7.28/

I'm happy to re-open the discussion if there are further issues, but preemptively closing for now.
