### ISSUE TITLE
Nodes must be 2-dimensional

### ISSUE THREAD

**Issue by zhangl** [dhermes/bezier#280]
raise ValueError("Nodes must be 2-dimensional, not", nodes_np.ndim)

this does not seems necessary, n dimensional nodes are fine as long as we do not plot them.

**Comment by dhermes** [comment]
@zhangl Can you provide more information, like which code path caused this error?

**Comment by zhangl** [comment]
Sorry for not being precise. The error came from calling bezier.Curve.from_nodes(nodes) when nodes are high dimensional.

https://github.com/dhermes/bezier/blob/e6925aad702842ae3637dfac9ff0da556ef0d980/src/python/bezier/_base.py#L121

**Comment by dhermes** [comment]
Thanks for that. So here the dimension is the dimension of the **data** (i.e. `nodes`), not the dimension of the Bézier curve.

See, e.g. https://github.com/dhermes/bezier/blob/2021.2.12/src/python/bezier/curve.py#L78-L81

> the columns represent each node while the rows are the dimension of the ambient space

So a `3 x 10` represents a degree 9 Bézier curve in `R^3`

----

I am going to pre-emptively close this as I hope I've been able to clear up the confusion. If I have misunderstood, let's re-open this issue and continue the discussion.
