### ISSUE TITLE
Determining Curvature k(s) Along Bezier Curve

### ISSUE THREAD

**Issue by yairg98** [dhermes/bezier#294]
I have been using this package for a school project which involves finding the curvature, k, at a given point along a Bezier curve. I thought I would be able to do that using the provided functionality, but my results so far have been pretty far off. Any help/guidance would be hugely appreciated.

**Comment by dhermes** [comment]
Thanks for asking! I **thought** it was in the `bezier.Curve` API but apparently it isn't.

There is however a function in `bezier.hazmat`:

https://bezier.readthedocs.io/en/2021.2.12/python/reference/bezier.hazmat.curve_helpers.html#bezier.hazmat.curve_helpers.get_curvature

----

I am going to preemptively close this issue as I **think** I've answered this for you. Let me know if this doesn't work and I am happy to re-open the issue and continue the discussion.
