### ISSUE TITLE
[Question] Get outline

### ISSUE THREAD

**Issue by moi15moi** [dhermes/bezier#299]
Is it possible to get the outline of an bezier shape with this tool?

If yes, it there an example available somewhere?

**Comment by dhermes** [comment]
@moi15moi I don't fully understand what you are asking. Two possible interpretations come to mind:

- Take a given curve and produce an image
- Take an image as input and spit out the nodes in a curve

Do either of these seem like what you're asking?

**Comment by moi15moi** [comment]
Sure!
Let's suppose I have a bezier that represent the white of my letter:
![image](https://user-images.githubusercontent.com/80980684/189772265-c5c2eeec-0b16-4631-bf9a-0ee9b7e78d2c.png)

Now, I would like to get the outline shape of this shape, so it is **almost** everything in red (I don't want to include the "semi circle").

Is that clearer ?

**Comment by dhermes** [comment]
@moi15moi It is somewhat clearer, yes. As far as I can tell you are asking if this library will "scan" your image and spit out the curves that define the boundary. No it will not do that.

Also keep in mind that Bézier curve **splines** are used for complex shapes, typically not a single (high degree) Bézier curve.

I am going to preemptively close this issue since (I think) I have answered your question. If I have mistakenly closed this issue, let me know and I am happy to re-open.

**Comment by moi15moi** [comment]
> As far as I can tell you are asking if this library will "scan" your image and spit out the curves that define the boundary.

No, I show an image to help you visualize what can of bezier I have: _Let's suppose I have a bezier that represent the white of my letter_
So, by that I mean that I have a node list that represent the white of the character __e__.

In reality, I can have a multiple list of **linear bezier** and **quadratic bezier**.
Why? Because, in the case of the letter **e**, I have 2 lists. One for the outline shape and one for the inline shape.
But, for the character **w**, I would only have 1 list.

### Example:
**"Complex" shape:**
![image](https://user-images.githubusercontent.com/80980684/189950461-23510191-819e-4053-810e-678bab67a409.png)

**What I want:**
I want to get the shape the outline, so a shape of everything in yellow.
How can I do that?

**Comment by moi15moi** [comment]
@dhermes Hi, is there a problem with my last message?

**Comment by dhermes** [comment]
No nothing was wrong with it, sorry for missing a reply from me.

From your response I think I can conclude you are looking for something to **process an image** but this library does not do that. It can **produce** an image via `matplotlib` and allows you to do lots of math on curve objects.
