### ISSUE TITLE
reverse evaluate

### ISSUE THREAD

**Issue by pdknsk** [dhermes/bezier#35]
I just discovered this package the other day, to make and debug [```cubic-bezier```](https://www.w3.org/TR/css-timing-1/#cubic-bezier-timing-functions) animations from *CSS*. I'd like to request or propose a feature. Take this example.

You have an animation that runs ```1s``` and animates an element from ```100``` to ```200``` height, according to some curve. At which time exactly does the element reach ```150``` height? So basically at which distance in the curve is ```y``` a certain value.

This can be easily figured out by using ```evaluate``` on the curve in intervals, with more than sufficient precision, but I'm wondering if a mathematically exact solution is possible.

**Comment by dhermes** [comment]
First, welcome @pdknsk! I recognize your handle from https://github.com/GoogleCloudPlatform/google-cloud-python

Second, it's totally possible. I don't have **any** support for things related to "when", but you could still find the answer with the current feature set (though via some non-public APIs).

Unfortunately, intersection is pretty tough, so (for now) it's only implemented in 2D. Since you only care about an intersection in 1D (it's really just polynomial root finding, which is do-able), we can "lie" and put the values on two lines:

```python
>>> import numpy as np
>>>
>>> # Put the real y-coordinates on the line x = 0
>>> nodes1 = np.asfortranarray([
...     [0.0, 100.0],
...     [0.0, 125.0],
...     [0.0, 200.0],
... ])
>>> # Put the intersection point in as the line y = 150
>>> nodes2 = np.asfortranarray([
...     [-1.0, 150.0],
...     [ 1.0, 150.0],
... ])
```

and then we just intersect those two line segments (using non-public API to get the parameter):

```python
>>> import bezier
>>> from bezier import _intersection_helpers
>>>
>>> curve1 = bezier.Curve.from_nodes(nodes1, _copy=False)
>>> curve2 = bezier.Curve.from_nodes(nodes2, _copy=False)
>>>
>>> intersections = _intersection_helpers.all_intersections([(curve1, curve2)])
>>> len(intersections)
1
>>> intersection = intersections[0]
>>> intersection.s
0.61803398874989468
>>> intersection.t
0.5
>>> intersection.get_point()
array([[   0.,  150.]])
```

So those would mean it reaches `150` height at `~0.618` seconds.

----

I'm not sure what the "correct" feature might be here. It'd probably be support for 1D intersections of `Curve` objects (not too difficult, since it's just polynomial root finding).

**Comment by dhermes** [comment]
> mathematically exact solution is possible.

This is a bit overloaded. In **all** cases, since IEEE-754 (`double` in C / `float` in Python / `number` in JS / etc.) numbers are rational, intersections are "algebraic" numbers that probably don't have good representations in IEEE-754.

For example, in base 16:

```
    4/3 = 1.555555555....
sqrt(2) = 1.6a09e667f3bcc908b2fb13...
```

but

```python
>>> (4.0 / 3).hex()
'0x1.5555555555555p+0'
>>> import numpy as np
>>> np.sqrt(2.0).hex()
'0x1.6a09e667f3bcdp+0'
```

**Comment by pdknsk** [comment]
Yep, I recognized you too. I found this project independent from the other project though. It's the first result for *site:python.org bezier* on Google.

I thought of a feature like ```distance_to_value``` first, but I suppose this really only applies to curves with constraints and characteristics like ```cubic-bezier```.

**Comment by dhermes** [comment]
@pdknsk D'oh! I forgot to mention the existence of `locate()`! (I somewhat forgot I had impl. this.)

```python
>>> import numpy as np
>>> import bezier
>>> 
>>> nodes = np.asfortranarray([
...     [0.0, 100.0],
...     [0.0, 125.0],
...     [0.0, 200.0],
... ])
>>> curve = bezier.Curve.from_nodes(nodes, _copy=False)
>>> point = np.asfortranarray([[0.0, 150.0]])
>>> curve.locate(point)
0.61803398874989957
```

and luckily, it also works in 1D!

```python
>>> import numpy as np
>>> import bezier
>>> 
>>> coefficients = np.asfortranarray([
...     [100.0],
...     [125.0],
...     [200.0],
... ])
>>> bezier_polynomial = bezier.Curve.from_nodes(coefficients, _copy=False)
>>> y_value = np.asfortranarray([[150.0]])
>>> bezier_polynomial.locate(y_value)
0.61803398874989957
```

**Comment by dhermes** [comment]
@pdknsk Is this sufficient? The [`Curve.locate()`][1] and [`Surface.locate()`][2] methods are **intended** to be an inverse / reverse of `evaluate()`.

[1]: http://bezier.readthedocs.io/en/0.4.0/reference/bezier.curve.html#bezier.curve.Curve.locate
[2]: http://bezier.readthedocs.io/en/0.4.0/reference/bezier.surface.html#bezier.surface.Surface.locate

**Comment by pdknsk** [comment]
In theory yes, but I don't know how to use it.

```Python
>>> curve = bezier.Curve.from_nodes(numpy.array([[0, 0], [1, 1]]))
>>> curve.evaluate(0.5)
array([[ 0.5,  0.5]])
>>> curve.locate(numpy.array([[0.5]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/bezier/curve.py", line 898, in locate
    point, 'Shape expected:', (1, self._dimension))
ValueError: ('Point is not in same dimension as curve', array([[ 0.5]]), 'Shape expected:', (1, 2))
```
Or with an actual curve.
```Python
>>> curve = bezier.Curve.from_nodes(numpy.array([[0, 0], [0.5, 0], [0.5, 1], [1, 1]]))
>>> curve.evaluate(0.5)
array([[ 0.5,  0.5]])
>>> curve.locate(numpy.array([[0.5]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/bezier/curve.py", line 898, in locate
    point, 'Shape expected:', (1, self._dimension))
ValueError: ('Point is not in same dimension as curve', array([[ 0.5]]), 'Shape expected:', (1, 2))
```

**Comment by dhermes** [comment]
@pdknsk The error message says whats wrong

> Point is not in same dimension as curve

i.e. your points are 1D (`[0.5`] in both cases), but your curves are 2D. What you'd want is to either locate an explicit 2D point:

```python
>>> nodes = np.asfortranarray([
...     [0.0, 0.0],
...     [0.5, 0.0],
...     [0.5, 1.0],
...     [1.0, 1.0],
... ])
>>> curve = bezier.Curve.from_nodes(nodes, _copy=False)
>>> curve
<Curve (degree=3, dimension=2)>
>>> point = curve.evaluate(0.5)
>>> point
array([[ 0.5,  0.5]])
>>> curve.locate(point)
0.5
```

or [project][1] the curve to the `x-` or `y-` dimension and then locate in 1D:

```python
>>> curve1d = bezier.Curve.from_nodes(nodes[:, [1]])
>>> curve1d
<Curve (degree=3, dimension=1)>
>>> curve1d.locate(np.asfortranarray([[0.5]]))
0.5
```

[1]: https://en.wikipedia.org/wiki/Projection_(linear_algebra)

**Comment by pdknsk** [comment]
Yes I got that, but didn't know how to supply the single value in the different shape (with ```x``` unknown), when the solution is to change the curve. I'm actually surprised this works, and verified the results against the method you posted earlier.

**Comment by dhermes** [comment]
@pdknsk So are you happy with this or is there more to discuss? Can this issue be closed? (Also, check out #36, inspired by you.)

**Comment by pdknsk** [comment]
Yep, can be closed. Thanks for your help! (I had to verify this really works with a few more curves.)

**Comment by dhermes** [comment]
Sure thing. RE: "really works", `locate()` just does as the [docs][1] state:

> Solves for `s` in `B(s) = p`.

[1]: http://bezier.readthedocs.io/en/0.4.0/reference/bezier.curve.html#bezier.curve.Curve.locate

**Comment by pdknsk** [comment]
What surprised me was two very different curves producing the same value.
```Python
>>> curve = bezier.Curve.from_nodes(numpy.array([[0, 0], [1, 0], [0, 1], [1, 1]]))
>>> bezier.Curve.from_nodes(curve.nodes[:, [1]]).locate(numpy.array([[0.25]]))
0.32635182233309518
>>> curve = bezier.Curve.from_nodes(numpy.array([[0, 0], [0, 0], [0, 1], [1, 1]]))
>>> bezier.Curve.from_nodes(curve.nodes[:, [1]]).locate(numpy.array([[0.25]]))
0.32635182233309518
```
That was only because I had confused the distance in the curve with the animation time for a second (or minute), until I noticed my mistake.
```Python
>>> curve = bezier.Curve.from_nodes(numpy.array([[0, 0], [1, 0], [0, 1], [1, 1]]))
>>> curve.evaluate(0.32635182233309518)
array([[ 0.47905547,  0.25      ]])
>>> curve = bezier.Curve.from_nodes(numpy.array([[0, 0], [0, 0], [0, 1], [1, 1]]))
>>> curve.evaluate(0.32635182233309518)
array([[ 0.03475827,  0.25      ]])
```

**Comment by dhermes** [comment]
Right, when you slice the `y`-axis (via `curve.nodes[:, [1]]`) they are no longer "very different curves", they are instead "the exact same polynomial", namely:

```
  0 (b_{0,3}) + 0 (b_{1,3}) + 1 (b_{2,3}) + 1 (b_{3,3})
= 3 s^2 (1 - s) + s^3
= s^2 [3 - 2 s]
```

**Comment by pdknsk** [comment]
I think adding simple helpers ```x_axis``` and ```y_axis``` might be useful.
```Python
bezier.Curve.from_nodes([curve.y_axis]).locate(numpy.array([[0.25]]))
```
Or perhaps even ```locate_x``` and ```locate_y``` to skip the intermediate step.
Or allow to supply ```None``` in some way.
```Python
curve.locate(x = None, y = 0.25)
```
(This is useful for this case, but I'm not sure about the usefulness in general.)

**Comment by dhermes** [comment]
> I'm not sure about the usefulness in general.

@pdknsk IMO that is too specific. `x_axis` and `y_axis` assume two things:

- The data in a `Curve` is two-dimensional
- The user considers their axes to be `x-` and `y-` (they could be swapped, or some other coordinate system, or just data, etc.)

But `Curve` can hold data in any dimension. `locate_x` and `locate_y` have the same issues.

----

It's not too bad to "write your own" `locate_x`:

```python
def locate_x(curve, value):
    if curve.dimension != 2:
        raise ValueError('Bad assumption')
    x_values = curve.nodes[:, [0]]
    new_curve = bezier.Curve.from_nodes(x_values)
    point1d = np.asfortranarray([[value]])
    return new_curve.locate(point1d)
```

**Comment by dhermes** [comment]
You could even write your own subclass:

```python
class Curve2D(bezier.Curve):

    _x_curve = None
    _y_curve = None

    def __init__(self, *args, **kwargs):
        super(Curve2D, self).__init__(*args, **kwargs)
        if self._dimension != 2:
            raise ValueError('Bad dimension')

    @property
    def x_curve(self):
        # Lazily compute / store this.
        if self._x_curve is None:
            self._x_curve = bezier.Curve(self._nodes[:, [0]], self._degree)
        return self._x_curve

    @property
    def y_curve(self):
        # Lazily compute / store this.
        if self._y_curve is None:
            self._y_curve = bezier.Curve(self._nodes[:, [1]], self._degree)
        return self._y_curve

    def locate_x(self, value):
        point1d = np.asfortranarray([[value]])
        return self.x_curve.locate(point1d)

    def locate_y(self, value):
        point1d = np.asfortranarray([[value]])
        return self.y_curve.locate(point1d)
```

**Comment by pdknsk** [comment]
That's a very elegant solution I think. I withdraw my idea.​

**Comment by dhermes** [comment]
It's definitely worth noting (for me) that people would be interested in **dedicated** 1D/2D/3D versions of these classes.

e.g. [`bezierjs`][1] **only** supports 2D and 3D (and FWIW, most of the algorithms in this library are limited to a small number of dimensions)

[1]: https://pomax.github.io/bezierjs/
