### ISSUE TITLE
Use Matthew Brett's `multibuild` for OS X wheels

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#46]
https://github.com/matthew-brett/multibuild

May also make sense to do this for Windows, but I'm hoping I can rig up a Docker-based set-up so I can do this by hand on Windows.

**Comment by dhermes** [comment]
Also:

- https://github.com/MacPython/wiki/wiki/Wheel-building
- https://github.com/MacPython/wiki/wiki/Spinning-wheels

**Comment by dhermes** [comment]
https://github.com/dhermes/bezier-wheels

**Comment by dhermes** [comment]
Not sure it's worth it? Made it possible to do in a mostly automated way with https://github.com/dhermes/bezier/commit/41c261ef3d6759376ada9704131627d0ac8bcf01 and that doesn't requiring having somewhere to upload wheels to get them out of Travis.

**Comment by dhermes** [comment]
This is at least used in 85f7619929debd3730d6ddafa4ac75789ad8e5f3, though it's unclear if `bezier-wheels` will get all the way off the ground for me.

**Comment by sharonahermes** [comment]
I am "lightly" using this and happy with all of the build processes for wheels.

**Comment by dhermes** [comment]
I am "lightly" using this and happy with all of the build processes for wheels.
